stages:
  - build

Build:
  stage: build
  image: ghcr.io/werf/werf:1.2-alpha
  script:
    - source <(werf ci-env gitlab)
    - werf build
  tags: ["kubernetes-runner-for-werf"]
  except:
    - main

Publish:
  stage: build
  image: ghcr.io/werf/werf:1.2-alpha
  script:
    - source <(werf ci-env gitlab)
    - werf bundle publish --tag 0.0.0-$(date +%s)
  tags: ["kubernetes-runner-for-werf"]
  only:
    - main
