stages:
- build
- test
- review
- prerelease-test
- release
- cleanup

default:
  image: ghcr.io/werf/werf:1.2-alpha-ubuntu
  before_script:
  - . $(werf ci-env gitlab --as-file)
  tags: [ "werf.kube-dev" ]

variables:
  CLUSTER_DOMAIN: kube-dev.flant.com
  TEST_NAMESPACE: ci-cd-with-gitops-tests
  WERF_AUTO_PULL_SECRET: "true"

.base_build:
  stage: build
  only:
  - main
  - merge_requests
  except:
  - schedules

Build emailservice:
  extends: ".base_build"
  script:
  - werf build emailservice emailservice-src

Build productcatalogservice:
  extends: ".base_build"
  script:
  - werf build productcatalogservice productcatalogservice-src

Build recommendationservice:
  extends: ".base_build"
  script:
  - werf build recommendationservice

Build shippingservice:
  extends: ".base_build"
  script:
  - werf build shippingservice shippingservice-src

Build checkoutservice:
  extends: ".base_build"
  script:
  - werf build checkoutservice checkoutservice-src

Build paymentservice:
  extends: ".base_build"
  script:
  - werf build paymentservice

Build currencyservice:
  extends: ".base_build"
  script:
  - werf build currencyservice

Build cartservice:
  extends: ".base_build"
  script:
  - werf build cartservice cartservice-src

Build frontend:
  extends: ".base_build"
  script:
  - werf build frontend frontend-src

Build adservice:
  extends: ".base_build"
  script:
  - werf build adservice

Build functional-tests:
  extends: ".base_build"
  script:
  - werf build functional-tests
  only:
  - main

.base_lint:
  stage: test
  only:
  - main
  - merge_requests
  except:
  - schedules

Lint frontend:
  extends: ".base_lint"
  script:
  - werf kube-run frontend-src --namespace $TEST_NAMESPACE -- make lint
  only:
    changes:
    - src/frontend/
    - pb/
    - werf.yaml
    - .gitlab-ci.yml

Lint productcatalogservice:
  extends: ".base_lint"
  script:
  - werf kube-run productcatalogservice-src --namespace $TEST_NAMESPACE -- make lint
  only:
    changes:
    - src/productcatalogservice/
    - pb/
    - werf.yaml
    - .gitlab-ci.yml

Lint shippingservice:
  extends: ".base_lint"
  script:
  - werf kube-run shippingservice-src --namespace $TEST_NAMESPACE -- make lint
  only:
    changes:
    - src/shippingservice/
    - pb/
    - werf.yaml
    - .gitlab-ci.yml

Lint checkoutservice:
  extends: ".base_lint"
  script:
  - werf kube-run checkoutservice-src --namespace $TEST_NAMESPACE -- make lint
  only:
    changes:
    - src/checkoutservice/
    - pb/
    - werf.yaml
    - .gitlab-ci.yml

Lint paymentservice:
  extends: ".base_lint"
  script:
  - werf kube-run paymentservice --namespace $TEST_NAMESPACE -- make lint
  only:
    changes:
    - src/paymentservice/
    - pb/
    - werf.yaml
    - .gitlab-ci.yml

Lint currencyservice:
  extends: ".base_lint"
  script:
  - werf kube-run currencyservice --namespace $TEST_NAMESPACE -- make lint
  only:
    changes:
    - src/currencyservice/
    - pb/
    - werf.yaml
    - .gitlab-ci.yml

.base_unit_tests:
  stage: test
  only:
  - main
  - merge_requests
  except:
  - schedules

Unit tests cartservice:
  extends: ".base_unit_tests"
  script:
  - werf kube-run cartservice-src --namespace $TEST_NAMESPACE -- make unit-tests
  only:
    changes:
    - src/cartservice/
    - pb/
    - werf.yaml
    - .gitlab-ci.yml

Unit tests frontend:
  extends: ".base_unit_tests"
  script:
  - werf kube-run frontend-src --namespace $TEST_NAMESPACE -- make unit-tests
  only:
    changes:
    - src/frontend/
    - pb/
    - werf.yaml
    - .gitlab-ci.yml

Unit tests productcatalogservice:
  extends: ".base_unit_tests"
  script:
  - werf kube-run productcatalogservice-src --namespace $TEST_NAMESPACE -- make unit-tests
  only:
    changes:
    - src/productcatalogservice/
    - pb/
    - werf.yaml
    - .gitlab-ci.yml

Unit tests shippingservice:
  extends: ".base_unit_tests"
  script:
  - werf kube-run shippingservice-src --namespace $TEST_NAMESPACE -- make unit-tests
  only:
    changes:
    - src/shippingservice/
    - pb/
    - werf.yaml
    - .gitlab-ci.yml

Unit tests checkoutservice:
  extends: ".base_unit_tests"
  script:
  - werf kube-run checkoutservice-src --namespace $TEST_NAMESPACE -- make unit-tests
  only:
    changes:
    - src/checkoutservice/
    - pb/
    - werf.yaml
    - .gitlab-ci.yml

.base_review:
  stage: review
  environment:
    name: review/$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME-$CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    url: https://$CI_PROJECT_NAME-$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME-$CI_MERGE_REQUEST_TARGET_BRANCH_NAME.$CLUSTER_DOMAIN
  variables:
    WERF_ENV: review
    WERF_SET_DOMAIN: domain=$CI_PROJECT_NAME-$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME-$CI_MERGE_REQUEST_TARGET_BRANCH_NAME.$CLUSTER_DOMAIN
    WERF_SET_ANNOTATIONS: annotations.nginx\.ingress\.kubernetes\.io/auth-url="http://basic-auth.kube-basic-auth.svc.cluster.local/argo"
  only:
  - merge_requests
  except:
  - schedules
  when: manual

Deploy review:
  extends: ".base_review"
  environment:
    on_stop: "Stop review"
  script:
  - werf converge

Stop review:
  extends: ".base_review"
  script:
  - werf dismiss --with-namespace
  environment:
    action: stop
  when: manual

Functional tests:
  stage: prerelease-test
  resource_group: functional-tests
  environment:
    name: functional-tests
  variables:
    WERF_SET_DOMAIN: domain=$CI_PROJECT_NAME-functional-tests.$CLUSTER_DOMAIN
    WERF_SET_ANNOTATIONS: annotations.nginx\.ingress\.kubernetes\.io/auth-url="http://basic-auth.kube-basic-auth.svc.cluster.local/argo"
  script:
  - werf converge
  only:
  - main
  except:
  - schedules

Publish release:
  stage: release
  script:
  - werf bundle publish --tag "0.1.${CI_PIPELINE_ID}"
  only:
  - main
  except:
  - schedules

Cleanup registry:
  stage: cleanup
  script:
  - werf cr login "$WERF_REPO"
  - werf cleanup
  only:
  - schedules
