stages:
- build

default:
  image: ghcr.io/werf/werf:1.2-alpha
  before_script:
  - source <(werf ci-env gitlab)
  tags: ["kubernetes-runner-for-werf"]

Publish:
  stage: build
  script:
  - werf bundle publish --tag 0.1.${CI_PIPELINE_ID}
  only:
  - main

Build:
  stage: build
  script:
  - werf build
  only:
  - merge_requests
