apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: boutique
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-url: http://basic-auth.kube-basic-auth.svc.cluster.local/argo
spec:
  rules:
  - host: boutique.kube-dev.flant.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
  tls:
  - hosts:
    - boutique.kube-dev.flant.com
    secretName: boutique-tls

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: boutique-tls
spec:
  commonName: boutique.kube-dev.flant.com
  dnsNames:
  - boutique.kube-dev.flant.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: boutique-tls

