apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: boutique
  annotations:
    kubernetes.io/ingress.class: nginx
    {{ $.Values.annotations | nindent 4 }}
spec:
  rules:
  - host: {{ $.Values.domain | required "$.Values.domain required" | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
  tls:
  - hosts:
    - {{ $.Values.domain | required "$.Values.domain required" | quote }}
    secretName: boutique-tls

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: boutique-tls
spec:
  commonName: {{ $.Values.domain | required "$.Values.domain required" | quote }}
  dnsNames:
  - {{ $.Values.domain | required "$.Values.domain required" | quote }}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: boutique-tls

